### PR TITLE
deltes refresh lock if error is caught

### PR DESCRIPTION
**Pull request by Brady-Conn**
Adds deletion of flight lock redis key if an error is encountered
Ticket: https://greenchef.atlassian.net/browse/WTF-578
Goes with: https://github.com/greenchef/bifrost/pull/37 but I need to merge this and make the 1.3.1 release first

### CODE REVIEW

**Comment by bearfact** [comment]
+1

**Comment by bearfact** [comment]
@Brady-Conn might be worth adding a TTL to the redisLock for extra safety

**Comment by Brady-Conn** [comment]
> @Brady-Conn might be worth adding a TTL to the redisLock for extra safety

I had thought about that, I couldn't decide on an amount of time though. What would you say 10 seconds?

**Comment by bearfact** [comment]
10 should be good

**Pull request merged**
